const USER_EMAIL = 'USER_EMAIL';
const USER_MOBILE_PHONE='USER_MOBILE_PHONE';
const USER_PASSWORD = 'USER_PASSWORD';
const USER_USERNAME = 'USER_USERNAME';

export {
  USER_EMAIL,
  USER_MOBILE_PHONE,
  USER_PASSWORD,
  USER_USERNAME
}