const AUTH0_ERROR = 'AUTH0_ERROR';
const AUTH0_REGISTERED = 'AUTH0_REGISTERED';
const AUTH0_SUCCESS = 'AUTH0_SUCCESS';
const AUTH0_TRIGGER = 'AUTH0_TRIGGER';

export {
  AUTH0_ERROR,
  AUTH0_REGISTERED,
  AUTH0_SUCCESS,
  AUTH0_TRIGGER
}